name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Change to the correct directory
      run: |
        cd workflows/github-codespace  # Navigate to the directory where package.json is

    - name: Install dependencies
      run: |
        npm ci  # This will install dependencies from package-lock.json

    - name: Run build (if present)
      run: |
        npm run build --if-present  # This is optional, only if you have a build script

    - name: Run tests
      run: |
        npm test  # Run tests (if defined in package.json)
